In [24]:
import numpy as np
arr = np.arange(30, 71)
print(arr)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


np.identity(3)

In [5]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
#or
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.randint(2,5,7)

array([0, 0, 0, 0, 0, 0, 0])

In [13]:
np.random.rand(3,5)

array([[0.27941026, 0.731631  , 0.52119845, 0.076893  , 0.50220939],
       [0.43413796, 0.85262836, 0.8995158 , 0.27914996, 0.30207816],
       [0.95728938, 0.57901676, 0.07918181, 0.95139675, 0.26668579]])

In [14]:
np.random.rand(15)

array([0.12433801, 0.22183591, 0.7691305 , 0.08329294, 0.22123764,
       0.03251673, 0.01006732, 0.3102096 , 0.64620856, 0.92975696,
       0.34979641, 0.45988072, 0.09413539, 0.80519685, 0.72532091])

In [18]:
l=np.ones(10)
l

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
m=np.zeros(10)
print(m)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
f= np.full(10, 5)
print(f)

[5 5 5 5 5 5 5 5 5 5]


In [21]:
np.vstack((l,m,f))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [30]:
arr=np.array([[5,0,7],[6,7,0],[7,5,5]])
print(arr==0)

[[False  True False]
 [False False  True]
 [False False False]]


In [33]:
print(arr!=0,"\n")
print(arr[arr!=0])

[[ True False  True]
 [ True  True False]
 [ True  True  True]] 

[5 7 6 7 7 5 5]


In [13]:
arr = np.array([1, 2, 3, 0, 6])
print(arr != 0)

[ True  True  True False  True]


In [14]:
arr[arr != 0]

array([1, 2, 3, 6])

In [11]:
arr1 = np.array([1, 2, 3, 4,0 ])
print(arr1 == 0)

[False False False False  True]


In [12]:
arr1[arr1 == 0]

array([0])

In [15]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 2.01, 3.02, 4.03, 5.04])
tolerance = 0.1
result = np.allclose(arr1, arr2, atol=tolerance)
print("Arrays are equal within a tolerance of", tolerance, ":", result)

Arrays are equal within a tolerance of 0.1 : True


In [25]:
vector = np.arange(15, 56)
print(vector[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [26]:
vector = np.random.randint(0, 11, size=5)
vector

array([ 2,  3,  0, 10,  1])

In [32]:
matrix = np.zeros((10, 10))
matrix[0, :] = 1
matrix[-1, :] = 1
matrix[:, 0] = 1
matrix[:, -1] = 1
matrix

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
matrix = np.zeros((5, 5))
matrix[0,0],matrix[1,1],matrix[2,2],matrix[3,3],matrix[4,4]=1,2,3,4,5
matrix

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [37]:
#or
matrix = np.zeros((5, 5))
np.fill_diagonal(matrix, [1, 2, 3, 4, 5])
print(matrix)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


In [38]:
matrix = np.ones((4, 4))
np.fill_diagonal(matrix, [0, 0, 0, 0])
print(matrix)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


In [39]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])
np.savez_compressed('arrays.npz', arr1=arr1, arr2=arr2)
data = np.load('arrays.npz')
arr1_loaded = data['arr1']
arr2_loaded = data['arr2']
print("Array 1:", arr1_loaded)
print("Array 2:", arr2_loaded)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]


In [40]:
array = np.random.rand(40)
selected_values = array[array > 0.5]
print("Original Array:")
print(array)
print("\nSelected Values:")
print(selected_values)

Original Array:
[0.03463743 0.67728103 0.17933785 0.9954038  0.86188019 0.52664498
 0.41103492 0.73739467 0.88040654 0.47739262 0.12345712 0.27432779
 0.68431692 0.99417919 0.90930414 0.78712685 0.9515988  0.41738798
 0.05322105 0.866104   0.769215   0.88198613 0.76116378 0.66527426
 0.96574067 0.78380333 0.24710647 0.23455857 0.14001934 0.57718066
 0.24998208 0.42271036 0.89224903 0.45358109 0.10787159 0.15699445
 0.10956641 0.01637443 0.64518722 0.59934719]

Selected Values:
[0.67728103 0.9954038  0.86188019 0.52664498 0.73739467 0.88040654
 0.68431692 0.99417919 0.90930414 0.78712685 0.9515988  0.866104
 0.769215   0.88198613 0.76116378 0.66527426 0.96574067 0.78380333
 0.57718066 0.89224903 0.64518722 0.59934719]
